#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGE_CALZADOS_JAGUAR")]
	public partial class GeneralDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public GeneralDataContext() : 
				base(global::SGE.DataAccess.Properties.Settings.Default.SGE_CALZADOS_JAGUARConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public GeneralDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GeneralDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GeneralDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GeneralDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SGET_TIPO_CAMBIO_MENSUAL_ACTUALIZAR")]
		public int SGET_TIPO_CAMBIO_MENSUAL_ACTUALIZAR([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tcamm_iid_anio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mesec_iid_mes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,4)")] System.Nullable<decimal> tcamm_ntipo_cambio_compra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,4)")] System.Nullable<decimal> tcamm_ntipo_cambio_venta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tcamm_iusuario_modifica, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tcamm_vpc_modifica)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tcamm_iid_anio, mesec_iid_mes, tcamm_ntipo_cambio_compra, tcamm_ntipo_cambio_venta, tcamm_iusuario_modifica, tcamm_vpc_modifica);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SGET_TIPO_CAMBIO_MENSUAL_ELIMINAR")]
		public int SGET_TIPO_CAMBIO_MENSUAL_ELIMINAR([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tcamm_icod_tcam_mensual)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tcamm_icod_tcam_mensual);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SGET_TIPO_CAMBIO_MENSUAL_INSERTAR")]
		public int SGET_TIPO_CAMBIO_MENSUAL_INSERTAR([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tcamm_iid_anio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mesec_iid_mes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,4)")] System.Nullable<decimal> tcamm_ntipo_cambio_compra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,4)")] System.Nullable<decimal> tcamm_ntipo_cambio_venta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tcamm_iusuario_crea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tcamm_vpc_crea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tcamm_iid_anio, mesec_iid_mes, tcamm_ntipo_cambio_compra, tcamm_ntipo_cambio_venta, tcamm_iusuario_crea, tcamm_vpc_crea);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SGET_TIPO_CAMBIO_MENSUAL_LISTAR")]
		public ISingleResult<SGET_TIPO_CAMBIO_MENSUAL_LISTARResult> SGET_TIPO_CAMBIO_MENSUAL_LISTAR()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SGET_TIPO_CAMBIO_MENSUAL_LISTARResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SGEG_TABLA_REGISTRO_POR_TIPO_TABLA")]
		public ISingleResult<SGEG_TABLA_REGISTRO_POR_TIPO_TABLAResult> SGEG_TABLA_REGISTRO_POR_TIPO_TABLA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tablc_iid_tipo_tabla)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tablc_iid_tipo_tabla);
			return ((ISingleResult<SGEG_TABLA_REGISTRO_POR_TIPO_TABLAResult>)(result.ReturnValue));
		}
	}
	
	public partial class SGET_TIPO_CAMBIO_MENSUAL_LISTARResult
	{
		
		private int _tcamm_icod_tcam_mensual;
		
		private System.Nullable<int> _tcamm_iid_anio;
		
		private System.Nullable<int> _mesec_iid_mes;
		
		private string _vdes_mesec_iid_mes;
		
		private System.Nullable<decimal> _tcamm_ntipo_cambio_compra;
		
		private System.Nullable<decimal> _tcamm_ntipo_cambio_venta;
		
		public SGET_TIPO_CAMBIO_MENSUAL_LISTARResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tcamm_icod_tcam_mensual", DbType="Int NOT NULL")]
		public int tcamm_icod_tcam_mensual
		{
			get
			{
				return this._tcamm_icod_tcam_mensual;
			}
			set
			{
				if ((this._tcamm_icod_tcam_mensual != value))
				{
					this._tcamm_icod_tcam_mensual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tcamm_iid_anio", DbType="Int")]
		public System.Nullable<int> tcamm_iid_anio
		{
			get
			{
				return this._tcamm_iid_anio;
			}
			set
			{
				if ((this._tcamm_iid_anio != value))
				{
					this._tcamm_iid_anio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesec_iid_mes", DbType="Int")]
		public System.Nullable<int> mesec_iid_mes
		{
			get
			{
				return this._mesec_iid_mes;
			}
			set
			{
				if ((this._mesec_iid_mes != value))
				{
					this._mesec_iid_mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vdes_mesec_iid_mes", DbType="VarChar(100)")]
		public string vdes_mesec_iid_mes
		{
			get
			{
				return this._vdes_mesec_iid_mes;
			}
			set
			{
				if ((this._vdes_mesec_iid_mes != value))
				{
					this._vdes_mesec_iid_mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tcamm_ntipo_cambio_compra", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> tcamm_ntipo_cambio_compra
		{
			get
			{
				return this._tcamm_ntipo_cambio_compra;
			}
			set
			{
				if ((this._tcamm_ntipo_cambio_compra != value))
				{
					this._tcamm_ntipo_cambio_compra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tcamm_ntipo_cambio_venta", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> tcamm_ntipo_cambio_venta
		{
			get
			{
				return this._tcamm_ntipo_cambio_venta;
			}
			set
			{
				if ((this._tcamm_ntipo_cambio_venta != value))
				{
					this._tcamm_ntipo_cambio_venta = value;
				}
			}
		}
	}
	
	public partial class SGEG_TABLA_REGISTRO_POR_TIPO_TABLAResult
	{
		
		private System.Nullable<int> _tarec_icorrelativo_registro;
		
		private string _tarec_vdescripcion;
		
		private string _tarec_vtipo_operacion;
		
		private int _tarec_iid_tabla_registro;
		
		private System.Nullable<char> _tarec_cestado;
		
		private System.Nullable<int> _tarec_iid_tabla_registro_ingreso;
		
		private System.Nullable<int> _tarec_iid_tabla_registro_salida;
		
		public SGEG_TABLA_REGISTRO_POR_TIPO_TABLAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarec_icorrelativo_registro", DbType="Int")]
		public System.Nullable<int> tarec_icorrelativo_registro
		{
			get
			{
				return this._tarec_icorrelativo_registro;
			}
			set
			{
				if ((this._tarec_icorrelativo_registro != value))
				{
					this._tarec_icorrelativo_registro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarec_vdescripcion", DbType="VarChar(100)")]
		public string tarec_vdescripcion
		{
			get
			{
				return this._tarec_vdescripcion;
			}
			set
			{
				if ((this._tarec_vdescripcion != value))
				{
					this._tarec_vdescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarec_vtipo_operacion", DbType="VarChar(2)")]
		public string tarec_vtipo_operacion
		{
			get
			{
				return this._tarec_vtipo_operacion;
			}
			set
			{
				if ((this._tarec_vtipo_operacion != value))
				{
					this._tarec_vtipo_operacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarec_iid_tabla_registro", DbType="Int NOT NULL")]
		public int tarec_iid_tabla_registro
		{
			get
			{
				return this._tarec_iid_tabla_registro;
			}
			set
			{
				if ((this._tarec_iid_tabla_registro != value))
				{
					this._tarec_iid_tabla_registro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarec_cestado", DbType="Char(1)")]
		public System.Nullable<char> tarec_cestado
		{
			get
			{
				return this._tarec_cestado;
			}
			set
			{
				if ((this._tarec_cestado != value))
				{
					this._tarec_cestado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarec_iid_tabla_registro_ingreso", DbType="Int")]
		public System.Nullable<int> tarec_iid_tabla_registro_ingreso
		{
			get
			{
				return this._tarec_iid_tabla_registro_ingreso;
			}
			set
			{
				if ((this._tarec_iid_tabla_registro_ingreso != value))
				{
					this._tarec_iid_tabla_registro_ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarec_iid_tabla_registro_salida", DbType="Int")]
		public System.Nullable<int> tarec_iid_tabla_registro_salida
		{
			get
			{
				return this._tarec_iid_tabla_registro_salida;
			}
			set
			{
				if ((this._tarec_iid_tabla_registro_salida != value))
				{
					this._tarec_iid_tabla_registro_salida = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
