using System;

namespace SGE.Entity
{
    public class ERequerimientoMaterial : EAuditoria
    {
        public int rqmac_iid_requerimiento_material { get; set; }
        public string rqmac_icod_requerimiento_material { get; set; }
        public int rqmac_iorden_produccion { get; set; }
        public DateTime rqmac_sfecha_requerimiento_material { get; set; }
        public int rqmac_iproceso { get; set; }
        public int rqmac_ipedido { get; set; }
        public int rqmac_iitem_pedido { get; set; }
        public int rqmac_ificha_tecnica { get; set; }
        public int rqmac_ioperario { get; set; }
        public int rqmac_imodelo { get; set; }
        public string DesModelo { get; set; }
        public int rqmac_icolor { get; set; }
        public int rqmac_imarca { get; set; }
        public string DesMarca { get; set; }
        public int rqmac_itipo { get; set; }
        public int rqmac_iserie { get; set; }
        public int rqmac_ilinea { get; set; }
        public int rqmac_talla1 { get; set; }
        public int rqmac_talla2 { get; set; }
        public int rqmac_talla3 { get; set; }
        public int rqmac_talla4 { get; set; }
        public int rqmac_talla5 { get; set; }
        public int rqmac_talla6 { get; set; }
        public int rqmac_talla7 { get; set; }
        public int rqmac_talla8 { get; set; }
        public int rqmac_talla9 { get; set; }
        public int rqmac_talla10 { get; set; }
        public int rqmac_cant_talla1 { get; set; }
        public int rqmac_cant_talla2 { get; set; }
        public int rqmac_cant_talla3 { get; set; }
        public int rqmac_cant_talla4 { get; set; }
        public int rqmac_cant_talla5 { get; set; }
        public int rqmac_cant_talla6 { get; set; }
        public int rqmac_cant_talla7 { get; set; }
        public int rqmac_cant_talla8 { get; set; }
        public int rqmac_cant_talla9 { get; set; }
        public int rqmac_cant_talla10 { get; set; }
        public long? rqmac_iid_kardex1 { get; set; }
        public long? rqmac_iid_kardex2 { get; set; }
        public long? rqmac_iid_kardex3 { get; set; }
        public long? rqmac_iid_kardex4 { get; set; }
        public long? rqmac_iid_kardex5 { get; set; }
        public long? rqmac_iid_kardex6 { get; set; }
        public long? rqmac_iid_kardex7 { get; set; }
        public long? rqmac_iid_kardex8 { get; set; }
        public long? rqmac_iid_kardex9 { get; set; }
        public long? rqmac_iid_kardex10 { get; set; }
        public int? rqmac_icod_producto1 { get; set; }
        public int? rqmac_icod_producto2 { get; set; }
        public int? rqmac_icod_producto3 { get; set; }
        public int? rqmac_icod_producto4 { get; set; }
        public int? rqmac_icod_producto5 { get; set; }
        public int? rqmac_icod_producto6 { get; set; }
        public int? rqmac_icod_producto7 { get; set; }
        public int? rqmac_icod_producto8 { get; set; }
        public int? rqmac_icod_producto9 { get; set; }
        public int? rqmac_icod_producto10 { get; set; }
        public int rqmac_iid_almacen { get; set; }
        public DateTime? rqmac_sfecha_ing_kardex { get; set; }
        public int rqmac_iid_situacion { get; set; }
        public int rqmac_ntotal { get; set; }
        public decimal rqmac_ndocenas { get; set; }
        public string rqmac_vcodigo_producto { get; set; }
        public string rqmac_vdescripcion_producto { get; set; }
        public int intusuario { get; set; }
        public string vpc { get; set; }
        public bool rqmac_flag_estado { get; set; }
        public int rqmac_tipo { get; set; }
        public int rqmac_isituacion { get; set; }
        public string strsituacion { get; set; }
        public string strtipo { get; set; }
        public string strcolor { get; set; }
        public string resec_vdescripcion { get; set; }
        public string strpedido { get; set; }
        public int stritempedido { get; set; }
        public string strfichatecnica { get; set; }
        public string strlinea { get; set; }
        public string strordenproduccion { get; set; }
        public string strproceso { get; set; }
        public string stroperario { get; set; }
        public string stralmacen { get; set; }
        public int rqmac_cant_aprocesar1 { get; set; }
        public int rqmac_cant_aprocesar2 { get; set; }
        public int rqmac_cant_aprocesar3 { get; set; }
        public int rqmac_cant_aprocesar4 { get; set; }
        public int rqmac_cant_aprocesar5 { get; set; }
        public int rqmac_cant_aprocesar6 { get; set; }
        public int rqmac_cant_aprocesar7 { get; set; }
        public int rqmac_cant_aprocesar8 { get; set; }
        public int rqmac_cant_aprocesar9 { get; set; }
        public int rqmac_cant_aprocesar10 { get; set; }
        public string pedido { get; set; }
        public string situacion { get; set; }
    }
}
